# Generated by Django 5.0.2 on 2024-02-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('profession', models.CharField(blank=True, max_length=300)),
                ('age', models.IntegerField(default=0)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=200)),
                ('en_profil', models.BooleanField(default=True)),
            ],
        ),
    ]
