# Generated by Django 5.0.2 on 2024-03-04 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_section_block_subblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='block',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='block',
            name='paragraph1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='block',
            name='paragraph2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='block',
            name='paragraph3',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('picture1', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('short_description', models.TextField(blank=True)),
                ('paragraph1', models.TextField(blank=True)),
                ('paragraph2', models.TextField(blank=True)),
                ('paragraph3', models.TextField(blank=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='cv.portfoliotype')),
            ],
        ),
        migrations.DeleteModel(
            name='SubBlock',
        ),
    ]
