# Generated by Django 5.0.2 on 2024-03-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_portfoliotype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='title',
            new_name='name',
        ),
    ]
