# Generated by Django 5.0.2 on 2024-03-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_rename_title_portfolio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
