# Generated by Django 5.0.2 on 2024-03-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_block_file_portfolio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='pos_index',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='portfoliotype',
            name='pos_index',
            field=models.IntegerField(default=100),
        ),
    ]
