# Generated by Django 5.0.2 on 2024-03-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_portfolio_pos_index_portfoliotype_pos_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('object', models.CharField(max_length=300)),
                ('text', models.TextField()),
            ],
        ),
    ]
