# Generated by Django 5.0.2 on 2024-03-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_visitormessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitormessage',
            options={'ordering': ['-recieving_date']},
        ),
        migrations.AddField(
            model_name='visitormessage',
            name='recieving_date',
            field=models.TimeField(auto_now=True),
        ),
    ]
