# Generated by Django 5.0.2 on 2024-03-08 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_alter_visitormessage_recieving_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitormessage',
            options={'ordering': ['-receiving_date']},
        ),
        migrations.RenameField(
            model_name='visitormessage',
            old_name='recieving_date',
            new_name='receiving_date',
        ),
    ]
