# Generated by Django 5.0.2 on 2024-03-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_alter_visitormessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='web_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
